version: '3.8'

# This file provides convenient aliases for running commands inside containers
# It's automatically loaded by docker-compose

services:
  mcphub:
    # Enable interactive mode by default
    stdin_open: true
    tty: true
    
  # Service for running one-off commands
  run:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mcphub:dev
    container_name: mcphub-run
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-this}
      - DATABASE_URL=postgresql://mcphub:mcphub_password@postgres:5432/mcphub?schema=public
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BASE_PATH=${BASE_PATH:-}
    volumes:
      - ./src:/app/src
      - ./frontend:/app/frontend
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./tsconfig.json:/app/tsconfig.json
      - ./jest.config.cjs:/app/jest.config.cjs
      - ./mcp_settings.json:/app/mcp_settings.json
      - ./data:/app/data
      - ./servers.json:/app/servers.json
      - node_modules:/app/node_modules
      - frontend_node_modules:/app/frontend/node_modules
    working_dir: /app
    command: /bin/sh
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mcphub-network
    profiles:
      - tools